apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-api-server
        image: ${REGISTRY_PATH}/apiserver:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred-gar