apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-api-server
        image: ${CI_IP_ADDRESS_AND_PORT}/kiss/prokube-images/apiserver:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred