apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server
spec:
  template:
    spec:
      containers:
      - name: server
        image: ${REGISTRY_PATH}/kiss/prokube-images/cacheserver:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
