apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-persistenceagent
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        image: ${REGISTRY_PATH}/kiss/prokube-images/persistenceagent:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
