apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-scheduledworkflow
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-scheduledworkflow
        image: ${CI_IP_ADDRESS_AND_PORT}/kiss/prokube-images/scheduledworkflow:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
