apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-scheduledworkflow
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-scheduledworkflow
        image: ${REGISTRY_PATH}/scheduledworkflow:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred-gar
