apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-viewer-crd
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-viewer-crd
        image: ${CI_IP_ADDRESS_AND_PORT}/kiss/prokube-images/viewercontroller:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
