apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-viewer-crd
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-viewer-crd
        image: ${REGISTRY_PATH}/viewercontroller:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred-gar
